CREATE TABLE IF NOT EXISTS departments (
id SERIAL NOT NULL,
name VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS employee (
id SERIAL NOT NULL,
name VARCHAR(255) NOT NULL,
department_id int NOT NULL,
chief_id int DEFAULT NULL,
PRIMARY KEY(id),
FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY (chief_id) REFERENCES employee(id) ON DELETE NO ACTION ON UPDATE NO ACTION
);